#version 430

// work‐group size; tune to your GPU and volume size
layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

// the sphere details which do the carving. x,y,z are typical position and the w is the radius
layout readonly uniform vec4 sphereDetails;

// the model matrix of the color volume 
layout readonly uniform mat4 modelMatrix;

// binding 0: output coloured volume (8-bit RGBA image)
layout(binding = 0, rgba32f) writeonly uniform image3D colorVolume;

void main() {
    ivec3 dimensions = imageSize(colorVolume);
    ivec3 coord = ivec3(gl_GlobalInvocationID.xyz);

    if (coord.x >= dimensions.x || coord.y >= dimensions.y || coord.z >= dimensions.z)
    {
        return;
    }

    vec3 pos = modelMatrix * gl_GlobalInvocationID.xyz;
    
    float distanceToSphere = length(pos - sphereDetails.xyz);
    
    vec4 color = imageLoad(colorVolume, coord);

    if (distanceToSphere <= sphereDetails.z)
    {
        color.a = 0.0;    
    }
    else
    {
        color.a = 1.0;
    }

    imageStore(colorVolume, coord, color);
}