#version 430
layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
layout (r32f, binding = 0) uniform image3D volumeTex;
uniform float scale;
uniform uint frame;

float rand(vec3 co) {
    return fract(sin(dot(co, vec3(12.9898,78.233,45.164))) * 43758.5453);
}

void main() {
    ivec3 coord = ivec3(gl_GlobalInvocationID.xyz);
    float r = rand(vec3(coord) + float(frame));
    float current = imageLoad(volumeTex, coord).r;
    imageStore(volumeTex, coord, vec4(current + r * scale, 0.0, 0.0, 1.0));
}